services:
    Octopouce\AdminBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false

    Octopouce\AdminBundle\Utils\FileUploader:
        arguments:
            $targetDirectory: '/uploads'

    Octopouce\AdminBundle\Form\EventSubscriber\TranslationFieldSubscriber:
        autowire: false
        autoconfigure: false
        public: false
        arguments:
            $locales: '%kernel.default_locale%'

    Octopouce\AdminBundle\EventListener\FileListener:
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    Octopouce\AdminBundle\Service\Sortable\PositionORMHandler:
        public: false
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionField', ['sort']]

    Octopouce\AdminBundle\Service\Featured\FeaturedORMHandler:
        public: false
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"