services:
    Octopouce\AdminBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false

    Octopouce\AdminBundle\Utils\FileUploader:
        arguments:
            $targetDirectory: '/uploads'

    Octopouce\AdminBundle\Form\EventSubscriber\TranslationFieldSubscriber:
        autowire: false
        autoconfigure: false
        arguments:
            $locales: '%kernel.default_locale%'

    Octopouce\AdminBundle\EventListener\FileListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    Octopouce\AdminBundle\Service\Sortable\PositionORMHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        calls:
            - [ 'setPositionField', ['sort']]

    Octopouce\AdminBundle\Doctrine\ORMInfo:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    Octopouce\AdminBundle\Provider\Locale\LocaleProvider:
        arguments:
            $defaultLocale: '%locale%'

    Octopouce\AdminBundle\Form\UserType:
        tags:
            - { name: form.type, alias: octopouce_admin_user_type }
