services:
    Octopouce\AdminBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false

    Octopouce\AdminBundle\Utils\FileUploader:
        arguments:
            $targetDirectory: '/uploads'

    Octopouce\AdminBundle\Form\EventSubscriber\TranslationFieldSubscriber:
        bind:
            $locales: '%app.locales%'

    Octopouce\AdminBundle\EventListener\FileListener:
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }